<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PN-HYDTECH-041" name="com.payswiff.tests.ServiceRequests_Validation" tests="5" failures="1" timestamp="22 Mar 2018 10:02:54 GMT" time="33.899" errors="0">
  <testcase name="DeInstallation_Validation" time="10.851" classname="com.payswiff.tests.ServiceRequests_Validation"/>
  <testcase name="HardwareIssues_Validation" time="6.014" classname="com.payswiff.tests.ServiceRequests_Validation">
    <failure type="java.lang.AssertionError" message="expected [] but found [Device Status]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Device Status]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.payswiff.tests.ServiceRequests_Validation.HardwareIssues_Validation(ServiceRequests_Validation.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- HardwareIssues_Validation -->
  <testcase name="Txn_SettlementValidation" time="5.693" classname="com.payswiff.tests.ServiceRequests_Validation"/>
  <testcase name="TxnSetttlemtnScreen_Validation" time="5.716" classname="com.payswiff.tests.ServiceRequests_Validation"/>
  <testcase name="InsSetttlemtnScreen_Validation" time="5.625" classname="com.payswiff.tests.ServiceRequests_Validation"/>
</testsuite> <!-- com.payswiff.tests.ServiceRequests_Validation -->
